"use client";

import Image from "next/image";
import { memo, useEffect, useRef, useState } from "react";
import type { ResumeData, TemplateId } from "@/types/resume";
import ResumeRenderer from "@/components/templates/ResumeRenderer";

/** Natural A4 width in pixels that each template is designed for. */
const TEMPLATE_NATURAL_WIDTH = 794;

interface TemplateThumbnailProps {
  templateId: TemplateId;
  data: ResumeData;
  accentColor?: string;
  /** Extra Tailwind classes applied to the outer container. */
  className?: string;
}

// ── 1. Static PNG thumbnail ──────────────────────────────────────────────────

interface StaticThumbnailProps {
  templateId: TemplateId;
  className: string;
  onError: () => void;
}

function StaticThumbnail({ templateId, className, onError }: StaticThumbnailProps) {
  return (
    <div className={`relative w-full bg-white ${className}`} style={{ aspectRatio: "210 / 297" }}>
      <Image
        src={`/template-previews/${templateId}.png`}
        alt={`${templateId} template preview`}
        fill
        sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw"
        className="object-contain object-top"
        onError={onError}
        priority={false}
      />
    </div>
  );
}

// ── 2. Live-render fallback ──────────────────────────────────────────────────

interface LiveThumbnailProps {
  templateId: TemplateId;
  data: ResumeData;
  accentColor?: string;
  className: string;
}

function LiveThumbnail({ templateId, data, accentColor, className }: LiveThumbnailProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [scale, setScale] = useState(0.35);

  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;

    const update = (w: number) => { if (w > 0) setScale(w / TEMPLATE_NATURAL_WIDTH); };
    update(el.getBoundingClientRect().width);

    const observer = new ResizeObserver(([entry]) => update(entry.contentRect.width));
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  return (
    <div
      ref={containerRef}
      className={`relative w-full overflow-hidden bg-white ${className}`}
      style={{ aspectRatio: "210 / 297" }}
    >
      <div
        style={{
          position: "absolute",
          top: 0,
          left: 0,
          width: `${TEMPLATE_NATURAL_WIDTH}px`,
          transformOrigin: "top left",
          transform: `scale(${scale})`,
          pointerEvents: "none",
          userSelect: "none",
        }}
      >
        <ResumeRenderer data={data} templateId={templateId} accentColor={accentColor} />
      </div>
    </div>
  );
}

// ── 3. Placeholder when neither PNG nor live render is available ──────────────

function ThumbnailPlaceholder({ className }: { className: string }) {
  return (
    <div
      className={`relative flex w-full items-center justify-center bg-slate-100 ${className}`}
      style={{ aspectRatio: "210 / 297" }}
    >
      <div className="flex flex-col items-center gap-2 text-slate-400">
        <svg width="32" height="40" viewBox="0 0 32 40" fill="none" aria-hidden="true">
          <rect x="1" y="1" width="30" height="38" rx="3" stroke="currentColor" strokeWidth="1.5" />
          <line x1="7" y1="12" x2="25" y2="12" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
          <line x1="7" y1="18" x2="25" y2="18" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
          <line x1="7" y1="24" x2="20" y2="24" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
        </svg>
        <span className="text-[10px] font-medium">Preview unavailable</span>
      </div>
    </div>
  );
}

// ── Composed component ────────────────────────────────────────────────────────

type ThumbnailMode = "static" | "live" | "placeholder";

/**
 * Template gallery thumbnail.
 *
 * Loading strategy (in priority order):
 *   1. Static PNG  → /template-previews/{id}.png (instant, zero JS cost)
 *   2. Live render → React component scaled to fit via ResizeObserver
 *   3. Placeholder → SVG document icon (last resort)
 *
 * The static PNG is generated by:
 *   npm run generate-thumbnails
 */
function TemplateThumbnailInner({
  templateId,
  data,
  accentColor,
  className = "",
}: TemplateThumbnailProps) {
  const [mode, setMode] = useState<ThumbnailMode>("static");

  // If the template changes, retry the static PNG first
  useEffect(() => { setMode("static"); }, [templateId]);

  if (mode === "static") {
    return (
      <StaticThumbnail
        templateId={templateId}
        className={className}
        onError={() => setMode("live")}
      />
    );
  }

  if (mode === "live") {
    return (
      <LiveThumbnail
        templateId={templateId}
        data={data}
        accentColor={accentColor}
        className={className}
      />
    );
  }

  return <ThumbnailPlaceholder className={className} />;
}

export const TemplateThumbnail = memo(TemplateThumbnailInner);
