export type AtsSectionKey =
  | "summary"
  | "skills"
  | "experience"
  | "education"
  | "projects"
  | "certifications";

export interface AtsConfig {
  analysisReferenceDateIso: string;
  weights: {
    keyword: number;
    section: number;
    experience: number;
    quality: number;
  };
  sectionPoints: Record<AtsSectionKey, number>;
  contactPoints: {
    email: number;
    phone: number;
    linkedin: number;
  };
  sectionAliases: Record<AtsSectionKey, string[]>;
  synonyms: Record<string, string[]>;
  stopWords: string[];
  noiseWords: string[];
  actionVerbs: string[];
  softSkills: string[];
  certificationSignals: string[];
  toolPlatformSignals: string[];
  quality: {
    idealWordCountMin: number;
    idealWordCountMax: number;
    shortWordCountThreshold: number;
    longWordCountThreshold: number;
    minBulletPoints: number;
    idealBulletPoints: number;
    maxBulletPoints: number;
    minActionVerbs: number;
    idealActionVerbs: number;
    minQuantifiedAchievements: number;
    idealQuantifiedAchievements: number;
  };
  keywordExtraction: {
    maxKeywords: number;
    minPhraseLength: number;
    maxPhraseWords: number;
    minimumPhraseScore: number;
  };
  experience: {
    noJobDescriptionScore: number;
    underOneYearScore: number;
    oneToThreeYearsScore: number;
    threeToFiveYearsScore: number;
    fivePlusYearsScore: number;
    extraPositionBonus: number;
  };
  optimization: {
    maxOptimizedBulletsPerRole: number;
    maxSuggestedSkills: number;
    maxGapKeywords: number;
  };
}

export const atsConfig: AtsConfig = {
  analysisReferenceDateIso: "2026-05-22T00:00:00.000Z",
  weights: {
    keyword: 40,
    section: 20,
    experience: 20,
    quality: 20,
  },
  sectionPoints: {
    summary: 3,
    skills: 5,
    experience: 5,
    education: 3,
    projects: 2,
    certifications: 2,
  },
  contactPoints: {
    email: 3,
    phone: 3,
    linkedin: 2,
  },
  sectionAliases: {
    summary: [
      "summary",
      "professional summary",
      "career summary",
      "profile",
      "about me",
      "objective",
      "career objective",
      "professional profile",
    ],
    skills: [
      "skills",
      "technical skills",
      "core skills",
      "core competencies",
      "competencies",
      "key skills",
      "skills & tools",
      "skills and tools",
    ],
    experience: [
      "experience",
      "work experience",
      "professional experience",
      "employment history",
      "career history",
      "relevant experience",
    ],
    education: [
      "education",
      "academic background",
      "academics",
      "qualifications",
    ],
    projects: [
      "projects",
      "project experience",
      "selected projects",
      "personal projects",
    ],
    certifications: [
      "certifications",
      "certification",
      "licenses",
      "licenses & certifications",
      "licenses and certifications",
      "credentials",
      "credentials and certifications",
    ],
  },
  synonyms: {
    AEM: ["Adobe Experience Manager", "Adobe Experience Manager Sites"],
    JavaScript: ["JS", "ECMAScript"],
    TypeScript: ["TS"],
    "REST API": ["RESTful API", "REST Services", "REST APIs"],
    "CI/CD": ["continuous integration", "continuous delivery", "continuous deployment"],
    AWS: ["Amazon Web Services"],
    Azure: ["Microsoft Azure"],
    GCP: ["Google Cloud Platform"],
    React: ["React.js", "ReactJS"],
    "Node.js": ["NodeJS", "Node"],
    Docker: ["Docker Compose", "containerization"],
    Kubernetes: ["K8s", "kubernetes"],
    SQL: ["Structured Query Language"],
    Agile: ["Scrum", "Kanban"],
    GraphQL: ["GraphQL API"],
    HTML: ["HTML5"],
    CSS: ["CSS3"],
    Git: ["GitHub", "GitLab"],
    Jira: ["JIRA"],
    Salesforce: ["Sales Cloud"],
    Snowflake: ["Snowflake Data Cloud"],
    DevOps: ["site reliability", "SRE"],
    Tableau: ["Tableau Desktop"],
    PowerBI: ["Power BI"],
    Python: ["Py"],
    Java: ["JDK"],
    "Adobe Analytics": ["Analytics"],
    "A/B Testing": ["split testing"],
    Terraform: ["IaC"],
    "Apache Sling": ["Sling"],
    OSGi: ["OSGi Services"],
    "Spring Boot": ["SpringBoot"],
    Kafka: ["Apache Kafka"],
    MongoDB: ["Mongo"],
    PostgreSQL: ["Postgres"],
    MySQL: ["MariaDB"],
  },
  stopWords: [
    "a",
    "about",
    "above",
    "after",
    "again",
    "against",
    "all",
    "am",
    "an",
    "and",
    "any",
    "are",
    "as",
    "at",
    "be",
    "because",
    "been",
    "before",
    "being",
    "below",
    "between",
    "both",
    "but",
    "by",
    "can",
    "could",
    "did",
    "do",
    "does",
    "doing",
    "down",
    "during",
    "each",
    "few",
    "for",
    "from",
    "further",
    "had",
    "has",
    "have",
    "having",
    "he",
    "her",
    "here",
    "hers",
    "herself",
    "him",
    "himself",
    "his",
    "how",
    "i",
    "if",
    "in",
    "into",
    "is",
    "it",
    "its",
    "itself",
    "just",
    "more",
    "most",
    "my",
    "myself",
    "no",
    "nor",
    "not",
    "of",
    "off",
    "on",
    "once",
    "only",
    "or",
    "other",
    "our",
    "ours",
    "ourselves",
    "out",
    "over",
    "own",
    "same",
    "she",
    "should",
    "so",
    "some",
    "such",
    "than",
    "that",
    "the",
    "their",
    "theirs",
    "them",
    "themselves",
    "then",
    "there",
    "these",
    "they",
    "this",
    "those",
    "through",
    "to",
    "too",
    "under",
    "until",
    "up",
    "very",
    "was",
    "we",
    "were",
    "what",
    "when",
    "where",
    "which",
    "while",
    "who",
    "whom",
    "why",
    "with",
    "would",
    "you",
    "your",
    "yours",
    "yourself",
    "yourselves",
  ],
  noiseWords: [
    "responsible",
    "responsibilities",
    "experience",
    "experienced",
    "including",
    "including",
    "team",
    "teams",
    "project",
    "projects",
    "work",
    "working",
    "role",
    "roles",
    "ability",
    "skills",
    "skill",
    "knowledge",
    "development",
    "developer",
    "solution",
    "solutions",
    "business",
    "company",
    "customer",
    "customers",
    "client",
    "clients",
    "strong",
    "good",
    "great",
    "excellent",
    "ability",
    "hands-on",
    "hands on",
    "familiar",
    "familiarity",
    "proficient",
    "proficiency",
    "support",
    "supported",
    "using",
    "use",
    "used",
    "utilized",
    "deliver",
    "delivered",
    "manage",
    "managed",
    "engineer",
    "engineering",
    "developer",
    "development",
    "designer",
    "design",
    "manager",
    "management",
    "analyst",
    "analysis",
    "architect",
    "architecture",
    "consultant",
    "administrator",
    "specialist",
    "director",
    "lead",
    "senior",
    "junior",
    "principal",
    "frontend",
    "front-end",
    "backend",
    "back-end",
    "full-stack",
    "full stack",
  ],
  actionVerbs: [
    "developed",
    "built",
    "designed",
    "implemented",
    "created",
    "led",
    "managed",
    "optimized",
    "integrated",
    "automated",
    "delivered",
    "improved",
    "launched",
    "reduced",
    "increased",
    "collaborated",
    "engineered",
    "orchestrated",
    "streamlined",
    "architected",
    "migrated",
    "deployed",
    "coordinated",
    "mentored",
    "analyzed",
    "established",
    "scaled",
    "shipped",
    "resolved",
    "standardized",
  ],
  softSkills: [
    "leadership",
    "communication",
    "collaboration",
    "stakeholder management",
    "problem solving",
    "problem-solving",
    "teamwork",
    "presentation",
    "facilitation",
    "mentoring",
    "coaching",
    "adaptability",
    "ownership",
    "critical thinking",
    "analytical thinking",
    "prioritization",
    "organization",
  ],
  certificationSignals: [
    "certified",
    "certification",
    "credential",
    "certificate",
    "license",
    "pmp",
    "csm",
    "scrum master",
    "aws certified",
    "google cloud certified",
    "azure certified",
    "adobe certified",
  ],
  toolPlatformSignals: [
    "docker",
    "kubernetes",
    "terraform",
    "ansible",
    "jira",
    "confluence",
    "slack",
    "service now",
    "servicenow",
    "salesforce",
    "snowflake",
    "tableau",
    "power bi",
    "figma",
    "postman",
    "jenkins",
    "gitlab",
    "github",
    "bitbucket",
    "sonarqube",
    "elastic",
    "splunk",
    "datadog",
    "new relic",
    "hibernate",
    "spring",
    "node",
    "react",
    "graphql",
    "redis",
    "mongodb",
    "postgres",
    "mysql",
  ],
  quality: {
    idealWordCountMin: 200,
    idealWordCountMax: 1000,
    shortWordCountThreshold: 200,
    longWordCountThreshold: 1500,
    minBulletPoints: 3,
    idealBulletPoints: 8,
    maxBulletPoints: 18,
    minActionVerbs: 5,
    idealActionVerbs: 8,
    minQuantifiedAchievements: 2,
    idealQuantifiedAchievements: 4,
  },
  keywordExtraction: {
    maxKeywords: 25,
    minPhraseLength: 2,
    maxPhraseWords: 4,
    minimumPhraseScore: 2,
  },
  experience: {
    noJobDescriptionScore: 100,
    underOneYearScore: 35,
    oneToThreeYearsScore: 60,
    threeToFiveYearsScore: 80,
    fivePlusYearsScore: 100,
    extraPositionBonus: 5,
  },
  optimization: {
    maxOptimizedBulletsPerRole: 6,
    maxSuggestedSkills: 8,
    maxGapKeywords: 8,
  },
};
